### PR TITLE
Ported to 1.9.4

### PR DESCRIPTION
**Pull request by GirafiStudios**

### CODE REVIEW

**Comment by squeek502** [comment]
Thanks :smile:

**Comment by superckl** [comment]
Is 12.16.1.1908 still a valid version for 1.9.4? I can't find it on the downloads page and the project won't compile with it. (Invalid version)

**Comment by GirafiStudios** [comment]
No LexManos took it down the day after he released it. It worked just fine when I did this PR tho.

**Comment by squeek502** [comment]
Bumped Forge version (https://github.com/squeek502/ASMHelper/commit/267ecd3fb47f2323b80ce23783af338af34055b4) just in case.

**Pull request merged**
